### ISSUE TITLE
Как добавить транк мультифона?

### ISSUE THREAD

**Issue by krll-k** [antirek/docker-asterisk#1]
До этого использовал FreePBX, но т.к. мне нужна возможность отправлять смс, и прочие вещи, решил освоить чистый Asterisk. У меня есть конфиг от FreePBX, правильно я понимаю что следуют в конец sip.conf дописать

<pre>
username=7##########
type=peer
secret=########
qualify=yes
nat=yes
insecure=port,invite
host=sbc.megafon.ru
fromuser=7##########
fromdomain=multifon.ru
dtmfmode=inband
disallow=all
allow=alaw
context=from-trunk

7##########@multifon.ru:########:7##########@sbc.megafon.ru:5060/7##########
</pre>

**Comment by antirek** [comment]
а) в чем вопрос? добавьте и проверьте.
б) по чистому астериску есть хорошие ресурсы поддержки: asterisk-support.ru, forum.asterisk.ru, chat.asterisk-support.ru
